### ISSUE TITLE
Crash when trying to rename unnamed function (e.g. sub_1234)

### ISSUE THREAD

**Issue by mewmew** [REDasmOrg/REDasm#5]
Hi Antonio!

I just discovered REDasm today, and I am really quite amazed! It looks great, and I can see there is great potential. Everything went smooth with the binary I analyzed, it was possible to decode the jump tables of switch statements, the function imports, the segments and also cross reference locations in the assembly listing.

However, when I tried to renamed an unnamed function (e.g. `sub_1234`) by pressing `n` and entering a new name (e.g. `foo`), REDasm crashed.

The following is the crash info:

```
u@x1 ~/D/REDasm> coredumpctl info 27074
           PID: 27074 (REDasm)
           UID: 1000 (u)
           GID: 985 (users)
        Signal: 11 (SEGV)
     Timestamp: Tue 2018-11-06 00:35:03 CET (1min 3s ago)
  Command Line: ./REDasm
    Executable: /home/u/Desktop/REDasm/REDasm
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (u)
       Boot ID: ab6b7cd61cc440208b6fcdaec8e1d3da
    Machine ID: 792fb0e702064dae88e8cd719872ab6d
      Hostname: x1
       Storage: /var/lib/systemd/coredump/core.REDasm.1000.ab6b7cd61cc440208b6fcdaec8e1d3da.27074>
       Message: Process 27074 (REDasm) of user 1000 dumped core.
                
                Stack trace of thread 27074:
                #0  0x00007febc9a89d9f x86_64_fallback_frame_state (libgcc_s.so.1)
                #1  0x00007febc9a8ba58 _Unwind_Backtrace (libgcc_s.so.1)
                #2  0x00007febc99bfcc6 __backtrace (libc.so.6)
                #3  0x00007febc5214bee n/a (libQt5WebEngineCore.so.5)
                #4  0x00007febc5214d00 n/a (libQt5WebEngineCore.so.5)
                #5  0x00007febc5215337 n/a (libQt5WebEngineCore.so.5)
                #6  0x00007febc9c353c0 __restore_rt (libpthread.so.0)
                #7  0x0000000000000031 n/a (n/a)
```

And gdb backtrace:
```
Core was generated by `./REDasm'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  x86_64_fallback_frame_state (context=0x7fffc26db720, context=0x7fffc26db720, 
    fs=0x7fffc26db810) at ./md-unwind-support.h:63
63	./md-unwind-support.h: No such file or directory.
[Current thread is 1 (Thread 0x7febb52cdfc0 (LWP 27074))]
(gdb) bt
#0  x86_64_fallback_frame_state (context=0x7fffc26db720, context=0x7fffc26db720, 
    fs=0x7fffc26db810) at ./md-unwind-support.h:63
#1  uw_frame_state_for (context=context@entry=0x7fffc26db720, fs=fs@entry=0x7fffc26db810)
    at /build/gcc/src/gcc/libgcc/unwind-dw2.c:1265
#2  0x00007febc9a8ba58 in _Unwind_Backtrace (trace=0x7febc99bfb40 <backtrace_helper>, 
    trace_argument=0x7fffc26db9d0) at /build/gcc/src/gcc/libgcc/unwind.inc:302
#3  0x00007febc99bfcc6 in backtrace () from /usr/lib/libc.so.6
#4  0x00007febc5214bee in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#5  0x00007febc5214d00 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#6  0x00007febc5215337 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#7  <signal handler called>
#8  0x0000000000000031 in ?? ()
#9  0x000055fceb6248c2 in ListingItemModel::onListingChanged(REDasm::ListingDocumentChanged const*) ()
#10 0x000055fceb6153cd in REDasm::ListingDocument::removeSorted(unsigned long, unsigned int) ()
#11 0x000055fceb615fa9 in REDasm::ListingDocument::symbol(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int) ()
#12 0x000055fceb6164b6 in REDasm::ListingDocument::rename(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#13 0x000055fceb639e25 in DisassemblerTextView::renameCurrentSymbol() ()
#14 0x000055fceb63a71d in DisassemblerTextView::keyPressEvent(QKeyEvent*) ()
#15 0x00007febca8f6ca8 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007febca99ccef in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007febca99f9e5 in QAbstractScrollArea::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007febca8b6e14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#19 0x00007febca8bf6a3 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#20 0x00007febc9eb7c39 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#21 0x00007febca9145c0 in ?? () from /usr/lib/libQt5Widgets.so.5
#22 0x00007febca8b6e14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#23 0x00007febca8be6e1 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#24 0x00007febc9eb7c39 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#25 0x00007febca27c892 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /usr/lib/libQt5Gui.so.5
#26 0x00007febca282046 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#27 0x00007febca25ba3c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#28 0x00007febb4f06dad in ?? () from /usr/lib/libQt5XcbQpa.so.5
#29 0x00007febc9eb68cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#30 0x00007febc9ebebc6 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#31 0x000055fceb5728c4 in main ()
```

Let me know if there is any other information that may help to troubleshoot this issue.

Cheerful regards,
Robin

**Comment by Dax89** [comment]
Hi Robin!
First of all: thanks for trying REDasm!

The issue is here, during symbol's replacement in listing:
```
#9  0x000055fceb6248c2 in ListingItemModel::onListingChanged(REDasm::ListingDocumentChanged const*) ()
#10 0x000055fceb6153cd in REDasm::ListingDocument::removeSorted(unsigned long, unsigned int) ()
#11 0x000055fceb615fa9 in REDasm::ListingDocument::symbol(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int) ()
#12 0x000055fceb6164b6 in REDasm::ListingDocument::rename(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
```

I can't reproduce with my binaries, is it possible to share the one that triggers this issue?
Thanks!

**Comment by Dax89** [comment]
Ok, I understand!

I'm on Telegram, I can create a group.

**Comment by Dax89** [comment]
Is this issue still valid with the latest nightlies?
https://github.com/REDasmOrg/REDasm-Builds

**Comment by mewmew** [comment]
Hi Antonio!

I'll give it a look, soon as I get a chance :) Just started first week of Uni while on an exchange to Korea. So, have a bit to get settled in to the study life and culture. After that, I'd be glad to check out REDasm! If I don't make any sound by the next few weeks, feel free to ping me!

Have spring wishes.

Cheers,
Robin

**Comment by Dax89** [comment]
Thanks, no problem!

**Comment by mewmew** [comment]
I tried out the latest version and I've not been able to reproduce the issue on this revision. As such, I'll close this issue :)

Happy to see you continuing to work on REDasm! Wish you a happy spring :)

Cheers,
Robin
